### ISSUE TITLE
Outdated link in README

### ISSUE THREAD

**Issue by foundinblank** [fleetio/dbt-segment#13]
The link here (see screenshot) still points to the old version maintained by dbt labs. 

![CleanShot 2023-11-10 at 11 31 47@2x](https://github.com/fleetio/dbt-segment/assets/31513760/1cf63ea0-6054-4117-aa6f-c6937b8af439)

**Comment by jmhollinger** [comment]
@foundinblank Thanks for catching this. Just opened #14 to fix this in the README.
