### ISSUE TITLE
BigQuery: Type not found: text at [13:51]

### ISSUE THREAD

**Issue by fabianriewe** [fleetio/dbt-segment#18]
### Describe the bug
When running the package on BigQuery with package version 0.3.1 I get the following error:
```
Database Error in model segment_web_page_views (models/base/segment_web_page_views.sql)
  Type not found: text at [13:51]
  compiled Code at target/run/dbt_segment/models/base/segment_web_page_views.sql
  ```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

### Additional context
I think the bug was introduced by #17.

**Comment by 0adamjones** [comment]
@fabianriewe So sorry for the delay here, just merged a PR from @Klimmy that should fix this.
