### ISSUE TITLE
CONTEXT_CAMPAIGN_TYPE is not a field on Segment's page table

### ISSUE THREAD

**Issue by JonCrawford** [fleetio/dbt-segment#5]
### Describe the bug
The latest release expects Segment's source pageviews table to have a `context_campaign_type` column. This is a [non-standard UTM parameter](https://support.google.com/analytics/answer/1033863?hl=en#zippy=%2Cin-this-article) and represents a breaking change for anyone upgrading to the new repo/maintainers/version.

### Steps to reproduce
Attempt to use the new repo on a `pages` table without the custom `context_campaign_type` column.

### Expected results
Upgrading the package should have "just worked" or had breaking change warnings and/or migration instructions.

### Actual results
`invalid identifier 'CONTEXT_CAMPAIGN_TYPE'`

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [X] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.4.3
  - latest:    1.4.3 - Up to date!

Plugins:
  - snowflake: 1.4.1 - Up to date!
```

**Comment by johnh** [comment]
Same issue for us... this is not a standard field and therefore is not used by our marketing teams and does not exist in our .pages table.  

A work around could be to create this column but technically the schema is only managed by segment... and it sets a bad precedent

**Comment by jmhollinger** [comment]
@johnh @JonCrawford We are going to remove these static columns and utilize the existing `segment_pass_through_columns` project variable to specify additional columns. Should have a PR out today with the changes.
